name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (optional)

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Priyanshu-M-eng
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

      - name: Upload snake files
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist/
